import assert from 'node:assert/strict';
import {registerHoudiniTools} from '../../lib/tools.js';
import {HoudiniBridge} from '../../lib/bridge.js';
const definitions=new Map();let calls=0;
registerHoudiniTools({tools:{register:d=>definitions.set(d.name,d)}},{async exec(){calls++;return {ok:true,stdout:'',stderr:''}}});
const exec=definitions.get('houdini_exec');
assert(exec.parameters.required.includes('code'));
assert.equal(exec.parameters.properties.review,undefined);assert.equal(exec.parameters.properties.review_test,undefined);
assert.equal(HoudiniBridge.prototype.review,undefined);
await assert.rejects(exec.execute({review:{parent:'/obj/g',output:'/obj/g/OUT'}},{}),/missing required property/);
await assert.rejects(exec.execute({review_test:{}},{}),/missing required property/);
assert.equal(calls,0,'retired review payloads cannot reach the bridge');
assert.equal((await exec.execute({code:'__result__ = 1'},{})).ok,true);
assert.equal(calls,1);
console.log('independent review API removed; author exec remains available');
