import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
execFileSync(process.execPath,['tools/gen-web-polyfills.mjs','--check']);
const source=fs.readFileSync('houdini/python3.11libs/dsh_iterator_polyfill.js','utf8');
const context=vm.createContext({});
vm.runInContext('delete globalThis.Iterator; delete Array.prototype.toSorted',context);
assert.throws(()=>vm.runInContext('Iterator.prototype.join',context),/Iterator is not defined/);
assert.throws(()=>vm.runInContext('[2,1].toSorted()',context),/toSorted is not a function/);
vm.runInContext(source,context);
assert.equal(vm.runInContext('[1,2].values().map(x=>x*2).toArray().join(",")',context),'2,4');
assert.equal(vm.runInContext('new Map([[1,2]]).values().some(x=>x===2)',context),true);
assert.equal(vm.runInContext(`(()=>{
  const groups=[{id:'custom'},{id:'deepseek-official'},{id:'deepseek-account'}];
  const rank=id=>id==='deepseek-account'?0:id==='deepseek-official'?1:2;
  const ordered=groups.toSorted((a,b)=>rank(a.id)-rank(b.id));
  return ordered.map(g=>g.id).join(',')+'|'+groups.map(g=>g.id).join(',');
})()`,context),'deepseek-account,deepseek-official,custom|custom,deepseek-official,deepseek-account');
vm.runInContext('globalThis.savedIterator=Iterator;globalThis.savedMap=Iterator.prototype.map;globalThis.savedSorted=Array.prototype.toSorted',context);
vm.runInContext(source,context);
assert.equal(vm.runInContext('Iterator===savedIterator && Iterator.prototype.map===savedMap && Array.prototype.toSorted===savedSorted',context),true);
console.log('Runtime compatibility generation, missing-API repro, helpers, non-mutating model order and idempotence passed');
